In [18]:
import pandas as pd

read_file = pd.read_csv ('./SW_EpisodeVI.txt', sep= " ")

In [20]:
read_file.to_csv ('./data/SW_EpisodeVI.csv', index=None)

In [19]:
read_file

,line,character,dialogue
0,1,SHUTTLE CAPTAIN,"Command station, this is ST 321. Code Clearanc..."
1,2,DEATH STAR CONTROLLER,The security deflector shield will be deactiva...
2,3,SHUTTLE CAPTAIN,We're starting our approach.
3,4,OFFICER,Inform the commander that Lord Vader's shuttle...
4,5,OPERATOR,"Yes, sir."
...,...,...,...
669,670,LANDO,"Wedge, I don't think we're going to make it."
670,671,WEDGE,You'll make it. Just follow me Gold Leader.
671,672,LANDO,I promised to return his ship without a scratc...
672,673,HAN,Lando...
673,674,THREEPIO,They did it!