In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import re
import os
import sys
sys.path.append('../')

In [ ]:
for file in ls

In [18]:
read_file = pd.read_csv ('./SW_EpisodeIV.txt', sep= " ")

In [3]:
df = pd.read_csv('../data/SW_EpisodeIV.csv')

In [20]:
read_file.to_csv ('./data/SW_EpisodeVI.csv', index=None)

In [4]:
df

,line,character,dialogue,episode
0,1,THREEPIO,Did you hear that? They've shut down the main...,NaN
1,2,THREEPIO,We're doomed!,NaN
2,3,THREEPIO,There'll be no escape for the Princess this time.,NaN
3,4,THREEPIO,What's that?,NaN
4,5,THREEPIO,I should have known better than to trust the l...,NaN
...,...,...,...,...
1005,1006,LUKE,"Oh, no!",NaN
1006,1007,THREEPIO,"Oh, my! Artoo! Can you hear me? Say somethi...",NaN
1007,1008,TECHNICIAN,We'll get to work on him right away.,NaN
1008,1009,THREEPIO,"You must repair him! Sir, if any of my circui...",NaN
1009,1010,LUKE,He'll be all right.,NaN

In [ ]:
def download_dataset():
    '''Downloads a dataset from kaggle and only keeps the csv in your data file. Beware of your own data structure:
    this creates a data directory and also moves all the .csv files next to your jupyter notebooks to it.
    Takes: url from kaggle
    Returns: a folder with the downloaded and unzipped csv
    '''
    
    #Gets the name of the dataset.zip
    url = input("Introduce la url: ")
    
    #Gets the name ofA the dataset.zip
    endopint = url.split("/")[-1]
    #endopint was already like this 
    user = url.split("/")[-2]
    
    #Download, decompress and leaves only the csv
    download = f"kaggle datasets download -d {user}/{endopint}"
    decompress = f"unzip *.zip"
    delete = f"rm -rf *.zip"
    make_directory = "mkdir data"
    lista = "ls >> archivos.txt"
    
    for i in [download, decompress, delete, lista]:
        os.system(i)
    
    #Move the csv to uour data folder
    for file in list("./archivos.txt"):
        os.system(f"mv *.csv ./data/{file}")
        f"{file}>> archivos_csv.txt"
    return None

download_dataset()